name: NuGet

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
            DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0

        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
                  check-latest: true
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '6.0.x'
                  include-prerelease: true

            - name: Build with dotnet
              run: |
                  cd backend
                  dotnet pack --configuration Release --output ./artifacts
                  # dotnet nuget add source https://nuget.pkg.github.com/BhanuKorthiwada/index.json -n github -u BhanuKorthiwada -p ${{ secrets.GH_TOKEN }} --store-password-in-clear-text
                  # dotnet nuget push ./artifacts/*.nupkg --source "github" --api-key ${{ secrets.GH_TOKEN }} --skip-duplicate
                  ## until dotnet nuget push ./artifacts/*.nupkg --skip-duplicate --no-symbols true; do echo "Retrying"; sleep 1; done

            - uses: actions/upload-artifact@v2
              with:
                  name: nuget-packages
                  path: ./artifacts
